[project]
name = "probabilistic-pca"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "edward>=1.3.5",
    "h5py>=3.14.0",
    "ipython>=8.37.0",
    "matplotlib>=3.10.6",
    "tensorflow>=2.20.0",
]
